# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b06bb6ae0b17afc7093bcc9d923c740a1e54943416cac84ab7f709da5b1045105e8c49cb79584126045e654c46a6a3d9f9a3d21d119ff958a7facfcc46e1c4

test:
  secret_key_base: 5563fde1a12dc73d99112841b9bea24be698772b96d803154555419c41166d9f70268a14aa7777166388ae38c7447461e8cc987a67e1d270c4398a73e1b45063

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
